import yaml
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

#import the configuration file
with open("config.yaml", "r") as file:
    config = yaml.safe_load(file)

def weatherPlot(df, show = True):
    """
    This function creates 4 plots based on the data that was previously fetched on the open weather API.
    Based on the current selection of variables, the plots display as follows:
    - One color per chosen location
    - different line types for different average values plotted on the same figure
    - different marker types for different daily values plotted on the same figure

    Short description of plots (from left to right and top to down):
    - min, max and average temperatures
    - precitipitations (total and snow fall)
    - sunrise and sunset times
    - sun time and day time

    The input is a dataframe generated by the weatherTransfo() function.
    The output is a timeries plot.

    """

    #set variables used in all the subplots

    #set colors for the locations
    colors = {config["Locations"]["name1"]: config["Plot"]["color1"], config["Locations"]["name2"]: config["Plot"]["color2"]}
    #set dictionnary that we will then unpack when setting labels for each subplot
    x_tick_var = config["Plot"]["x_axis_labels"]
    #set variable to set format of x-labels
    myFmt = mdates.DateFormatter(config["Plot"]["date_format"])
    #set marker size for all plots
    marks = config["Plot"]["marker_size"]

    #set number of plots (here 4)
    fig, axs = plt.subplots(2, 2, figsize=(config["Plot"]["figsize1"], config["Plot"]["figsize2"]))
    fig.subplots_adjust(hspace= config["Plot"]["adjust"])

    #get the first subplot (top-left)
    #plot is about temperature
    ax = axs[0, 0]

    for (loc, ty), group in df.groupby(["location","type"]):
        col = colors[loc]

        if ty == "Today":
            # no lines but just markers for today's data
            ax.plot(group["date"], group["t_avg"],marker= "o", markersize = marks, linestyle= "none", color = col) #, label=f'{loc} - {ty}')
            ax.plot(group["date"], group["t_max"],marker= "x", markersize = marks, linestyle= "none", color = col)
            ax.plot(group["date"], group["t_min"],marker= "d", markersize = marks, linestyle= "none", color = col)
        else:
            #lines for the 7-day mean
            ax.plot(group["date"], group["t_avg"], color = col)
            ax.plot(group["date"], group["t_max"], color = col, linestyle= "--")
            ax.plot(group["date"], group["t_min"], color = col, linestyle= ":")

    ax.set_xlabel("Date")
    ax.set_ylabel("temp")
    ax.set_title("Temp evolution over days (Min, Avg, Max) [°C]")
    ax.tick_params(**x_tick_var)
    ax.xaxis.set_major_formatter(myFmt)
    #ax.legend(title="Location")

    #get second plot (top-right)
    #plot is about total precipitation and snow
    ax = axs[0, 1]

    #replace 0 by nan so it doesn't get plotted
    for (loc, ty), group in df.replace(0, np.nan).groupby(["location","type"]):
        col = colors[loc]

        if ty == "Today":
            # no lines but just markers for today's data
            ax.plot(group["date"], group["prec_total"],marker= "o", markersize = marks, linestyle= "none", color= col)
            ax.plot(group["date"], group["snow"],marker= "x", markersize = marks, linestyle= "none", color = col)
            
        else:
            #lines for the 7-day mean
            ax.plot(group["date"], group["prec_total"], color = col)
            ax.plot(group["date"], group["snow"], color = col, linestyle= "--")

    ax.set_xlabel("Date")
    ax.set_ylabel("Precipitaion")
    ax.set_title("Precipitation and snow [mm]")
    ax.tick_params(**x_tick_var)
    ax.xaxis.set_major_formatter(myFmt)

    #get third plot (botom-left)
    #plot is about sunrise and sunset times (in hours since midnight)
    ax = axs[1, 0]

    for (loc, ty), group in df.groupby(["location","type"]):
        col = colors[loc]

        if ty == "Today":
            # no lines but just markers for today's data
            ax.plot(group["date"], group["sunrise"],marker= "o", markersize = marks, linestyle= "none", color= col)
            ax.plot(group["date"], group["sunset"],marker= "x", markersize = marks, linestyle= "none", color = col)
            
        else:
            #lines for the 7-day mean
            ax.plot(group["date"], group["sunrise"], color = col)
            ax.plot(group["date"], group["sunset"], color = col, linestyle= "--")

    ax.set_xlabel("Date")
    ax.set_ylabel("Hours since midnight")
    ax.set_title("Sunrise and sunset times [h]")
    ax.tick_params(**x_tick_var)
    ax.xaxis.set_major_formatter(myFmt)

    #get fourth plot (botom-right)
    #plot is about daytime and suntime in hours
    ax = axs[1, 1]

    for (loc, ty), group in df.groupby(["location","type"]):
        col = colors[loc]

        if ty == "Today":
            # no lines but just markers for today's data
            ax.plot(group["date"], group["day_time"],marker= "o", markersize = marks, linestyle= "none", color= col)
            ax.plot(group["date"], group["sun_time"],marker= "x", markersize = marks, linestyle= "none", color = col)
            
        else:
            #lines for the 7-day mean
            ax.plot(group["date"], group["day_time"], color = col)
            ax.plot(group["date"], group["sun_time"], color = col, linestyle= "--")

    ax.set_xlabel("Date")
    ax.set_ylabel("Hours")
    ax.set_title("Day time and sun time [h]")
    ax.tick_params(**x_tick_var)
    ax.xaxis.set_major_formatter(myFmt)

    if show:
        plt.show()
    
    return fig, axs